### ISSUE TITLE
RLey raises StandardError when building grammar

### ISSUE THREAD

**Issue by GuiHeurich** [famished-tiger/loxxy#2]
I tried opening IRB with the grammar file, and RLey raised the following error:
`1: from /var/lib/gems/2.7.0/gems/rley-0.7.07/lib/rley/syntax/grammar_builder.rb:116:in `grammar'
StandardError (Useless terminal symbol(s): CLASS, VAR.)`

When I removed both terminal symbols, it builds fine.

**Comment by famished-tiger** [comment]
Hello GuiHeurich, thanks for the notification.
You're right. The keyword CLASS was mispelled in lowercase in the grammar.
These quirks were solved by creating a parser and setting the Rley `diagnose` option on.
Lesson learned: don't push a grammar without a parser ...

**Comment by famished-tiger** [comment]
Hello Guilherme,
First of all, let me present the best wishes for a serene and rewarding year 2021 for you and your family.How is your work on the Ruby community progressing?

Concerning the issue you found an d reported in the mail below, it has been -luckily- fixed in the meantime.I made the mistake to commit the grammar a bit too early (without a parser to test its validity).
The error you discovered, is part of diagnostic checks built-in in Rley.
Maybe it"s interesting for you to know that in the initialize of the Parser classes, I force the diagnosis of the grammar:
        @engine = Rley::Engine.new do |cfg|          cfg.diagnose = true        end
On the checks Rley performs is to control a declared terminal is effectively used in at least one grammar rule.Otherwise, the terminal (symbol) can be considered as useless (hence the error message).
In reality, the CLASS and VAR appeared in rules but in ... lowercase ... That's the root cause of the error messages you discovered.
In the coming weeks, my progess on the Loxxy project won't have direct tangible results. The reason being that I have to ensure that all Loxxy expressions are correctly implemented.That will be a very iterative process.I hope that this won't discourage you to take a look on this new endeavour.
Kind regards,Dimitri
    On Thursday, December 31, 2020, 01:36:33 PM GMT+1, Gui Heurich <notifications@github.com> wrote:  
 
 


I tried opening IRB with the grammar file, and RLey raised the following error:
1: from /var/lib/gems/2.7.0/gems/rley-0.7.07/lib/rley/syntax/grammar_builder.rb:116:in grammar'
StandardError (Useless terminal symbol(s): CLASS, VAR.)`

When I removed both terminal symbols, it builds fine.
